# Generated by Django 3.2.23 on 2024-07-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('numeros', '0002_numberrecord_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number1', models.IntegerField()),
                ('number2', models.IntegerField()),
                ('result', models.IntegerField()),
            ],
            options={
                'db_table': 'numeros_numberrecord',
            },
        ),
    ]
